Update README.md with new products, new website link, AI principles and Strategic Roadmap
ai-cfia/.github pull request #17
Opened 2024-08-15 21:01 UTC by ClemZ31

This pull request updates the README.md file with new products, a new website link, AI principles, and the Strategic Roadmap for the Canadian Food Inspection Agency Artificial Intelligence Lab.

2024-08-20 13:54 UTC, RussellJimmies requested changes

2024-08-20 13:54 UTC, RussellJimmies commented on profile/README.md
> +* Nachet : vision par ordinateur appliquée aux images numériques issues du
...issues d'UN microscope, plutôt que DU?

2024-08-27 13:53 UTC, RussellJimmies approved these changes

2024-08-27 20:44 UTC, SonOfLope approved these changes

2024-08-29 13:52 UTC, nmeraihi approved these changes

2024-08-29 17:24 UTC, SonOfLope approved these changes

2024-08-30 13:48 UTC, merged